CREATE TABLE FABRICANTES
(
	CODIGO INT NOT NULL PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL
);

CREATE TABLE ARTICULOS
(
	CODIGO INT NOT NULL PRIMARY KEY,
    NOMBRE NVARCHAR(100),
    PRECIO INT,
    FK_FABRICANTE INT,
    CONSTRAINT FK_FABRICANTE FOREIGN KEY (FK_FABRICANTE) REFERENCES FABRICANTES(CODIGO) 
    ON DELETE CASCADE ON UPDATE CASCADE
);
