create database UD14_EJERCICIO_11;
use UD14_EJERCICIO_11;
CREATE TABLE FACULTAD
(
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE NVARCHAR(100) NOT NULL
);

CREATE TABLE INVESTIGADORES
(
	DNI VARCHAR(8) PRIMARY KEY,
    NOMBRE_APELLIDOS NVARCHAR(255) NOT NULL,
    COD_FACULTAD_I INT NOT NULL,
    CONSTRAINT COD_FACULTAD_I FOREIGN KEY (COD_FACULTAD_I) REFERENCES FACULTAD(CODIGO)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE EQUIPOS
(
	NUMSERIE CHAR(4) PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    COD_FACULTAD_E INT NOT NULL,
	CONSTRAINT COD_FACULTAD_E FOREIGN KEY (COD_FACULTAD_E) REFERENCES FACULTAD(CODIGO)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE RESERVA
(
	DNI_RES VARCHAR(8) NOT NULL,
    NUMSERIE_RES CHAR(4) NOT NULL,
    PRIMARY KEY (DNI_RES, NUMSERIE_RES),
	CONSTRAINT DNI_RES FOREIGN KEY (DNI_RES) REFERENCES INVESTIGADORES(DNI)
    ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT NUMSERIE_RES FOREIGN KEY (NUMSERIE_RES) REFERENCES EQUIPOS(NUMSERIE)
    ON DELETE CASCADE ON UPDATE CASCADE,
    COMIENZO DATETIME NOT NULL,
    FIN DATETIME NOT NULL
);