USE UD14_EJERCICIO_4;

CREATE TABLE DEPARTAMENTOS
(
	CODIGO INT PRIMARY KEY,
    NOMBRE NVARCHAR(100),
    PRESUPUESTO INT
);

CREATE TABLE EMPLEADOS
(
	DNI VARCHAR(8) PRIMARY KEY,
    NOMBRE NVARCHAR(100),
    APELLIDOS NVARCHAR(255),
    FK_DEPARTAMENTO INT,
    CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY (FK_DEPARTAMENTO) REFERENCES DEPARTAMENTOS(CODIGO)
    ON DELETE CASCADE ON UPDATE CASCADE
);