DROP DATABASE UD14_EJERCICIO_8;
CREATE DATABASE UD14_EJERCICIO_8;
USE UD14_EJERCICIO_8;

CREATE TABLE PIEZAS
(
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE NVARCHAR(100)
);

CREATE TABLE PROVEEDORES
(
	ID CHAR(4) PRIMARY KEY,
    NOMBRE NVARCHAR(100)
);

CREATE TABLE SUMINISTRA
(
	CODIGOPIEZA INT,
    IDPROVEEDOR CHAR(4),
    PRECIO INT,
    PRIMARY KEY(CODIGOPIEZA,IDPROVEEDOR),
    CONSTRAINT CODIGOPIEZA FOREIGN KEY (CODIGOPIEZA) REFERENCES PIEZAS(CODIGO)
    ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT IDPROVEEDOR FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDORES(ID)
    ON DELETE CASCADE ON UPDATE CASCADE
);

