USE UD14_EJERCICIO_8;

CREATE TABLE PIEZAS
(
	CODIGO INT PRIMARY KEY NOT NULL,
    NOMBRE NVARCHAR(100)
);

CREATE TABLE PROVEEDORES
(
	ID CHAR(4) PRIMARY KEY NOT NULL,
    NOMBRE NVARCHAR(100)
);

CREATE TABLE SUMINISTRA
(
	CODIGOPIEZA INT NOT NULL,
    IDPROVEEDOR CHAR(4) NOT NULL,
    PRECIO INT,
    PRIMARY KEY(CODIGOPIEZA,IDPROVEEDOR),
    CONSTRAINT CODIGOPIEZA FOREIGN KEY (CODIGOPIEZA) REFERENCES PIEZAS(CODIGO)
    ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT IDPROVEEDOR FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDORES(ID)
    ON DELETE CASCADE ON UPDATE CASCADE
);

