USE UD14_EJERCICIO_7;

CREATE TABLE DESPACHOS
(
	NUMERO INT PRIMARY KEY NOT NULL,
    CAPACIDAD INT
);

CREATE TABLE DIRECTORES
(
	DNI VARCHAR(8) PRIMARY KEY NOT NULL,
    NOMBREAPELLIDOS NVARCHAR(255),
    FK_DNIJEFE VARCHAR(8) NOT NULL,
    FK_DESPACHO INT NOT NULL,
	CONSTRAINT FK_DNIJEFE FOREIGN KEY (FK_DNIJEFE) REFERENCES DIRECTORES(DNI)
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_DESPACHO FOREIGN KEY (FK_DESPACHO) REFERENCES DESPACHOS(NUMERO)
    ON DELETE CASCADE ON UPDATE CASCADE
);