USE UD14_EJERCICIO_6;

CREATE TABLE PELICULAS
(
	CODIGO INT PRIMARY KEY,
    NOMBRE NVARCHAR(100),
    CALIFICACIONEDAD INT
);

CREATE TABLE SALAS
(
	CODIGO INT PRIMARY KEY,
    NOMBRE NVARCHAR(100),
    FK_PELICULA INT,
    CONSTRAINT FK_PELICULA FOREIGN KEY (FK_PELICULA) REFERENCES PELICULAS(CODIGO)
    ON DELETE CASCADE ON UPDATE CASCADE
);